name: Version Monitor
description: A Github action for monitoring versions and releases
branding:
  icon: anchor
  color: orange
inputs:
  file:
    description: The configuration file
    required: true
    default: "./package.json"
outputs:
  version:
    description: Current Version
  release:
    description: Current Release Version
runs:
  using: node16
  main: "dist/index.js"
